/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef query_CONSTANTS_H
#define query_CONSTANTS_H

#include "query_types.h"

namespace com { namespace mediav { namespace query {

class queryConstants {
 public:
  queryConstants();

};

extern const queryConstants g_query_constants;

}}} // namespace

#endif
