/**
 * Autogenerated by Thrift Compiler (0.9.2)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "query_constants.h"

namespace com { namespace mediav { namespace query {

const queryConstants g_query_constants;

queryConstants::queryConstants() {
}

}}} // namespace

